import styled from "styled-components"

export const Wrapper = styled.div`
    width:100%;height:100%;
    position: relative;
    .search{
        width:100%;height:1rem;
        display:flex;
        align-items:center;
        font-size:.3rem;
        border-bottom:1px solid #ccc;
        position: fixed;
        top:0;left:0;
        background:#fff;
        .back{
            width:.8rem;height:.8rem;
            background:yellow;
        }
        .search1{
            flex:1;height:.8rem;
            display:flex;padding-left:.3rem;
            div:nth-child(1){
                width:.8rem;
                height:100%;
                background:#EAEAEA;
                background:red;
            }
            input{
                flex:1;
                font-size:.3rem;
                background:#EAEAEA;
                outline:none;
                border:none;
            }
        }
        .select{
            width:.8rem;height:.8rem;
            background:yellow;
            line-height:.8rem;
            text-align:center;
        }
    }
    .sort{
        width:100%;
        height:1rem;
        display:flex;
        font-size:.4rem;
        align-items:center;
        justify-content:flex-start;
        padding-left:.2rem;
        position: fixed;
        top:1rem;left:0;
        background:#fff;
        .sort0{
            position: relative;
            .yincang{
                position:absolute;width:7.5rem;font-size:.26rem;
                top:.8rem;left:0;background:yellow;
                ul{
                    width:100%;
                    li{
                        width:100%;
                        height:.8rem;
                        line-height:.8rem;
                        border-bottom:1px solid #ccc;
                    }
                }
            }
        }
        .sort1{
            margin-left:.6rem;
        }
    }
    .goods{
        width:100%;
        height:100%;
        overflow:auto;
        padding-top:2rem;
        li{
            width:100%;height:2.5rem;
            display:flex;
            .left{
                width:30%;height:100%;
                img{
                    width:100%;height:100%;
                }
            }
            .right{
                width:65%;height:100%;border-bottom:1px solid #ccc;
                margin-left:5%;
                padding-left:.2rem;
                .title{
                    width:100%;height:1rem;font-size:.28rem;
                }
                .price{
                    width:100%;height:.5rem;font-size:.3rem;
                    color:red;line-height:.5rem;
                }
                .num{
                    width:100%;height:.5rem;font-size:.28rem;
                    margin-top:.2rem;
                    line-height:.5rem;font-size:.26rem;color:#ccc;
                    span{
                        color:red;
                    }
                }
            }
        }
    }
    .mask0{
        width:100%;height:100%;
        position:absolute;
        top:0;left:0;
        background:rgba(0,0,0,0.3)
    }
    .mask{
        width:100%;height:100%;
        position:absolute;
        top:0;left:100%;
        display:flex;
        justify-content:flex-end;
        .right{
            width:80%;height:100%;
            background:#fff;
            overflow:auto;
            position: relative;
            .one{
                padding-bottom:.1rem;
                border-bottom:1px solid #ccc;
                .title{
                    width:100%;height:.8rem;
                    display:flex;
                    justify-content:space-between;
                    align-items:center;
                    font-size:.3rem;
                    padding:0 .1rem;
                    .right0{
                        display:flex;
                        height:100%;
                        width:3rem;
                        justify-content:space-around;
                        align-items:center;
                        div:nth-child(1){
                            color:#fda208;
                            display:flex;

                        }
                    }
                }
                ul{
                    width:100%;
                    display:flex;
                    flex-wrap:wrap;
                    justify-content:flex-start;
                    li{
                        width:30%;height:.8rem;
                        background:#eee;
                        display:flex;
                        justify-content:center;
                        align-items:center;
                        border-radius:.1rem;
                        margin-right:3%;
                        margin-top:3%;
                    }
                }
            }
            .btns{
                width:100%;height:1rem;
                /* position:fixed; */
                position:absolute;
                display:flex;
                bottom:0;left:0%;
                background:#fff;
                div{
                    width:33%;
                    height:100%;
                    display:flex;
                    justify-content:center;
                    align-items:center;
                    font-size:.3rem;
                    span{
                        color:orange;
                    }
                }
                div:nth-child(2){
                    background:#eee;
                }
                div:nth-child(3){
                    background:orange;
                }
            }
        }
    }   

`